name: tl-detect
channels:
 - conda-forge
 - anaconda
dependencies:
 - python=3.5
 - ipykernel
 - numpy
 - pandas
 - opencv
 - matplotlib
 - pillow
 - cython
 - lxml
 - tk
 - pip:
   - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.6.0-cp35-cp35m-linux_x86_64.whl
